2025-02-20 09:23:53,581 ERROR scheduler Exception in Enqueue Events for Site library.test
Traceback (most recent call last):
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/silpc-067/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/silpc-067/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/silpc-067/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/silpc-067/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/silpc-067/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/silpc-067/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_473b6b06d3ef1825'@'localhost' (using password: YES)")
2025-02-25 12:35:01,855 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for site67.local
2025-02-25 12:35:01,956 ERROR scheduler Skipped queueing erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs because it was found in queue for site67.local
2025-02-25 12:47:31,449 ERROR scheduler Exception in Enqueue Events for Site site67.local
Traceback (most recent call last):
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/database/database.py", line 840, in get_single_value
    df = frappe.get_meta(doctype).get_field(fieldname)
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/__init__.py", line 1318, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/model/meta.py", line 70, in get_meta
    meta = Meta(doctype)
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/model/meta.py", line 124, in __init__
    super().__init__("DocType", doctype)
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/model/document.py", line 126, in __init__
    self.load_from_db()
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/model/meta.py", line 130, in load_from_db
    super().load_from_db()
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/model/document.py", line 199, in load_from_db
    self.set(df.fieldname, children)
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/model/base_document.py", line 237, in set
    self.extend(key, value)
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/model/base_document.py", line 304, in extend
    self.append(key, v)
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/model/base_document.py", line 263, in append
    d = self._init_child(value, key)
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/model/base_document.py", line 322, in _init_child
    value = get_controller(doctype)(value)
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/__init__.py", line 1601, in get_hooks
    hooks = _dict(cache.get_value("app_hooks", _load_app_hooks))
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 100, in get_value
    val = generator()
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/__init__.py", line 1568, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/__init__.py", line 1434, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/silpc-067/frappe-bench/apps/todo_app/todo_app/hooks.py", line 3, in <module>
    from frappe.exceptions import Forbidden
ImportError: cannot import name 'Forbidden' from 'frappe.exceptions' (/home/silpc-067/frappe-bench/apps/frappe/frappe/exceptions.py)
2025-02-25 14:19:16,190 ERROR scheduler Exception in Enqueue Events for Site site67.local
Traceback (most recent call last):
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 102, in enqueue_events_for_site
    enqueue_events(site=site)
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 117, in enqueue_events
    all_jobs = frappe.get_all("Scheduled Job Type", filters={"stopped": 0}, fields="*")
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/__init__.py", line 2015, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/__init__.py", line 1990, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/model/db_query.py", line 192, in execute
    result = self.build_and_run()
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/model/db_query.py", line 207, in build_and_run
    args = self.prepare_args()
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/model/db_query.py", line 247, in prepare_args
    self.build_conditions()
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/model/db_query.py", line 581, in build_conditions
    self.build_filter_conditions(self.filters, self.conditions)
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/model/db_query.py", line 602, in build_filter_conditions
    conditions.append(self.prepare_filter_condition(f))
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/model/db_query.py", line 712, in prepare_filter_condition
    additional_filters_config = get_additional_filters_from_hooks()
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/boot.py", line 376, in get_additional_filters_from_hooks
    filter_hooks = frappe.get_hooks("filters_config")
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/__init__.py", line 1601, in get_hooks
    hooks = _dict(cache.get_value("app_hooks", _load_app_hooks))
  File "/home/silpc-067/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 96, in get_value
    val = pickle.loads(val)
AttributeError: Can't get attribute 'enforce_login' on <module 'todo_app.hooks' from '/home/silpc-067/frappe-bench/apps/todo_app/todo_app/hooks.py'>
2025-02-28 17:29:23,031 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for site67.local
2025-02-28 17:29:29,224 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for site67.local
2025-02-28 17:29:30,723 ERROR scheduler Skipped queueing payments.payment_gateways.doctype.razorpay_settings.razorpay_settings.capture_payment because it was found in queue for site67.local
